language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO=1.9.2
    - DJANGO=1.8.9
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q -e . --use-mirrors
    - pip install -r requirements.txt
script:
    - python runtests.py
