language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO=1.9.2
    - DJANGO=1.8.9
    - DJANGO=1.7.11
    - DJANGO=1.6.11
    - DJANGO=1.5.12
install:
    - pip install -q Django==$DJANGO
    - pip install -q -e .
    - pip install -r requirements.txt
script:
    - python runtests.py
